DROP TABLE IF EXISTS todo;
CREATE TABLE todo 
(
task_id VARCHAR(36) NOT NULL,
title VARCHAR(200) NOT NULL,
createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
dueDate DATE,
completed BOOLEAN
);


